services:
  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    command: npm start
    env_file:
      - ./frontend/.env.development.local
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
    ports:
      - '3001:3001'
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env.development.local
    stdin_open: true
    command: npm run start
