name: CI Pipeline

on:
  pull_request:
    branches: [develop, main]

jobs:
  frontend-quality-check:
    name: Frontend Code Quality Checks
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies in ci mode
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run Prettier (check)
        run: npm run format:check

      - name: Run Stylelint
        run: npm run stylelint

  backend-quality-check:
    name: Backend Code Quality Checks
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies in ci mode
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run Prettier (check)
        run: npm run format:check

  backend-unit-tests:
    name: Backend Unit Tests
    runs-on: ubuntu-latest
    needs: backend-quality-check

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test

  frontend-functional-tests:
    name: Frontend Functional Tests
    runs-on: ubuntu-latest
    needs: frontend-quality-check

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build frontend
        run: npm run build

      - name: Serve frontend
        run: |
          npm install -g serve
          serve -s build -l 3000 &

      - name: Wait for frontend to be ready
        run: |
          echo "Waiting for frontend..."
          while ! curl -s http://localhost:3000 > /dev/null; do
            sleep 2
          done

      - name: Run Cypress tests
        run: npx cypress run --browser chrome
        env:
          REACT_APP_BACKEND_URL: http://localhost:3001
