name: Code quality check, running Lint, Prettier and Stylelint

on:
  pull_request:
    branches: [develop, main]

jobs:
  quality-check:
    name: Code Quality Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies in ci mode
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run Prettier (check)
        run: npm run format:check

      - name: Run Stylelint
        run: npm run stylelint
